services:
  postgres:
    image: postgres:16-alpine
    container_name: turnero_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: turnero
      POSTGRES_PASSWORD: turnero
      POSTGRES_DB: turnero
    ports:
      - "5434:5432"
    volumes:
      - turnero_pgdata:/var/lib/postgresql/data

volumes:
  turnero_pgdata:
